### ISSUE TITLE
OMXFile - class for reading / writing to OMX files

### ISSUE THREAD

**Issue by wsp-mbuckley** [Transport-for-the-North/caf.toolkit#91]
Create new class for handling reading and writing OMX files, this should use either [PyTables](https://www.pytables.org/) or [H5Py](https://www.h5py.org/) packages as OMX files are just HDF5 files with a specific layout. A package already exists [OMX-python](https://github.com/osPlanning/omx-python) but it doesn't seem to be well maintained and would be simple enough to reimplement here.

A starting point for the class can be found in [NorMITs-demand on the MC_FE_WSP_main branch](https://github.com/Transport-for-the-North/NorMITs-Demand/blob/MC_FE_WSP_main/normits_demand/matrices/omx_file.py). Details of the OMX format can be found on the [Open Matrix GitHub](https://github.com/osPlanning/omx/wiki).

# Requirements
Class should be able to do the following

- Be accessed as a context manager (using `with`) so the file is closed and cleaned up automatically
- Read OMX files in versions 0.2 and 0.3 (and possibly others)
- Write OMX files which can be opened by SATURN and CUBE
- Access matrix levels as pandas DataFrames with zones as indices and columns
- Access zone information
- Provide methods for iterating through matrix levels

# Tasks

- [ ] Create `caf.toolkit.matrices` sub-package to contain omx module
- [ ] Write OMXFile class based on above specification
- [ ] Add unit tests for all functionality
- [ ] Add integration tests for testing the interaction with SATURN and CUBE
  - [ ] Can the class read files produced by both programs?
  - [ ] Can both programs read files created by the class?

**Comment by BenTaylor-TfN** [comment]
Transfer this issue to caf.mat @MattBuckley-TfN ?
