### ISSUE TITLE
UFMConverter - class for converting to / from SATURN's UFM files

### ISSUE THREAD

**Issue by wsp-mbuckley** [Transport-for-the-North/caf.toolkit#92]
Create new class for converting SATURN's UFM files into other matrix formats, this class will require SATURN to be installed and will expect the user to do that themselves. The class should use the various batch files provided with SATURN software for performing the conversions and should only act as a wrapper around them to make it easier to call them from Python.

A starting point for the class can be found in [NorMITs-demand normits_demand/matrices/ufm_converter.py](https://github.com/Transport-for-the-North/NorMITs-Demand/blob/master/normits_demand/matrices/ufm_converter.py). 

# Requirements
Class should be able to do the following

- Validate that SATURN is installed and available
- Setup an environment with access to the SATURN batch files
- Provide a simple method for running SATURN batch files using `subprocess.run`
- Validate the success of all the SATURN batch files, log any messages / command outputs and raise Python errors for any failures
- Convert the UFM files tothe following formats:
  - OMX
  - CSVs in TUBA2, TUBA3
- Convert to UFM files from the following formats:
  - OMX
  - CSVs in square format
- Provide functionality for basic UFM manipulation, including
  - Stacking and unstacking levels

# Tasks

- [ ] Create `caf.toolkit.matrices` sub-package to contain ufm module
- [ ] Write UFMConverter class based on above specification
- [ ] Add unit tests for all functionality, will require SATURN to be installed for full testing

**Comment by BenTaylor-TfN** [comment]
Transfer this issue to caf.mat @MattBuckley-TfN ?
