### ISSUE TITLE
MatConverter - class for converting to / from CUBE's mat format

### ISSUE THREAD

**Issue by wsp-mbuckley** [Transport-for-the-North/caf.toolkit#93]
Create new class for converting CUBE's '.mat' files into other matrix formats, this class will require CUBE to be installed and will expect the user to do that themselves. The class should use the functionality available in CUBE software for performing the conversions and should only act as a wrapper around them to make it easier to call them from Python.

A starting point for the class can be found in [NorMITs-demand normits_demand/matrices/cube_mat_converter.py](https://github.com/Transport-for-the-North/NorMITs-Demand/blob/master/normits_demand/matrices/cube_mat_converter.py). 

# Requirements
Class should be able to do the following

- Validate that CUBE is installed and available
- Setup an environment with access to CUBE Voyager
- Provide simple method for running CUBE Voyager scripts using `subprocess.run`
- Validate the success of all the CUBE Voyager scripts, log any messages / command outputs and raise Python errors for any failures
- Convert the `.mat` files to and from the following formats:
  - OMX
  - CSVs 

# Tasks

- [ ] Create `caf.toolkit.matrices` sub-package to contain cube module
- [ ] Write MatConverter class based on above specification
- [ ] Add unit tests for all functionality, will require CUBE to be installed for full testing

**Comment by BenTaylor-TfN** [comment]
@MattBuckley-TfN, is this relevant for caf.mat now instead?

**Comment by MattBuckley-TfN** [comment]
> @MattBuckley-TfN, is this relevant for caf.mat now instead? Should we transfer the issue?

yes definitely, this has also been partially complete in a recent PR
